account/urls.py
from django.conf.urls import url

from . import views

app_name = 'account'
urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^register/$', views.register, name='register'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^dash/$', views.dash, name='dash'),
    # Might be a better way to go about this one but just to test this is probably the best way....
    url(r'^create_new_invite_key/$', views.create_new_invite_key, name='create_new_invite_key'),

]

grapevine/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    # Admin
    url(r'^admin/', admin.site.urls),
    #  Home
    url(r'^', include('home.urls')),
    # Account
    url(r'^account/', include('account.urls')),
]

home/urls.py
from django.conf.urls import url

from . import views

# TODO Might Change this.... Might not!
app_name = 'home'
urlpatterns = [
    # Homepage
    url(r'^$', views.index, name='index'),
    # Details page
    url(r'^(?P<post_id>[0-9]+)/$', views.detail, name='detail'),
    # Add Comment
    url(r'^(?P<post_id>[0-9]+)/add_comment/$', views.addComment, name='add_comment'),
    # New Post
    url(r'^new_post/$', views.newPost, name='new_post'),
]

home/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from datetime import datetime
from django.conf import settings


"""
Database object for: Post
"""
@python_2_unicode_compatible
class Post(models.Model):
    post = models.TextField(max_length=1000)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    votes = models.IntegerField(default=0)
    date = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.post

"""
Database object for: Comment
"""
@python_2_unicode_compatible
class Comment(models.Model):
    comment = models.TextField(max_length=1000)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    votes = models.IntegerField(default=0)
    date = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.comment

home/forms.py
from django import forms
from .models import Post, Comment


"""
Form for: Adding a Post
"""
class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('post',)
        widgets = {
            'post': forms.Textarea(attrs={'class': 'comment-form-textarea'}),
        }


"""
Form for: adding a Comment
"""
class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('comment',)
        wigets = {
            'comment': forms.Textarea(attrs={'class': 'comment-form-textarea'}),
        }

home/views.py
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from datetime import datetime

from .models import Post, Comment
from .forms import PostForm, CommentForm

"""
View for: The homepage
"""
def index(request):
    if(request.user.is_authenticated()):
        print "[+] User is authenticated"
        post_list = Post.objects.order_by('-date')
        return render(request, 'home/index.html', {'post_list': post_list})
    else:
        print "[+] User is not authenticated"
        return render(request, 'home/index_unregistered.html')


"""
View for Adding a new post
Requires Login
"""
@login_required
def newPost(request):
    if request.method == "POST":
        post_form = PostForm(request.POST)
        print "[+] (Post) Post request has been received"
        if post_form.is_valid():
            post = post_form.save(commit=False)
            post.user = request.user
            post.save()
            return HttpResponseRedirect(reverse('home:detail', args=(post.id,)))

    else:
        print("[-] (Post) Get request received")
        post_form = PostForm()
        return render(request, 'home/new_post.html', {'post_form': post_form})


"""
View for: The requested posts details (Displays the post and the posts comments)
"""
@login_required
def detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    comment_form = CommentForm
    return render(request, 'home/detail.html', {'post': post, 'comment_form': comment_form})


"""
View for: adding a comment
"""
@login_required
def addComment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)

    if request.method == "POST":
        comment_form = CommentForm(request.POST)
        print "[+] Receievd a post request on addComment"

        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.user = request.user
            comment.save()
            return HttpResponseRedirect(reverse('home:detail', args=(post.id,)))

    else:
        return render(request, 'home/detail.html', {'post':post, 'comment_form':comment_form})

home/templates/home/about.html
{% extends "base.html"%}

{% block content %}
<h1>Man is least himself when he talks in his own person. Give him a mask, and he will tell you the truth - Oscar Wilde</h1>


{% endblock %}

home/templates/home/detail.html
{% extends "base.html" %}

{% block content %}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<div class="row">
  <div class="col-md-12">
    <div class="jumbotron">
      <p>{{ post.post }}</p>
      <p>Posted on: {{post.date }}</p>
      <p>Votes: {{ post.votes }}</p>
      <a href="#"><i class="fa fa-arrow-circle-up fa-3x fa-fw"></i></a>
      <a href="#"><i class="fa fa-arrow-circle-down fa-3x fa-fw"></i></a>
    </div>
  </div>
</div>



<div class="comment-form">
    {% if user.is_authenticated %}
    <h2>Add Comment<h2>
    <form action="{% url 'home:add_comment' post.id %}" method="POST" class="comment-form">
      {% csrf_token %}
      {{ comment_form.as_p }}
      <button type="submit" class="btn btn-primary">Add Comment</button>
    </form>
    {% endif %}
</div>


<h2>Comments</h2>
{% for comment in post.comment_set.all %}
<div class="row">
  <div class="col-md-12">
    <div class="jumbotron">
      <p>Comment: {{ comment.comment }}</p>
      <p>Votes: {{ comment.votes }}</p>
      <a href="#">Vote up</a>
      <a href="#">Vote Down</a>
      <p>Posted on: {{comment.date }}</p>
    </div>
  </div>
</div>
{% endfor %}




{% endblock %}

home/templates/home/index.html
{% extends "base.html" %}
{% block content %}
{% if post_list %}
  {% for post in post_list %}
  <div class="row">
    <div class="col-md-12">
      <div class="jumbotron">
        <p>{{ post.post }}</p>
        <!-- TODO  Sort out these up and down arrows and make them look sweet!-->
        <a href="#"><i class="fa fa-arrow-circle-up fa-3x fa-fw"></i></a>
        <a href="#"><i class="fa fa-arrow-circle-down fa-3x fa-fw"></i></a>

        <a href="{% url 'home:detail' post.id %}" class="btn btn-primary"><i class="fa fa-comments fa-fw"></i>(Num) Add Comment</a>
        <!-- TODO If the current user is equal to the user that created the post add a delete button-->
        <a href="{% url 'home:detail' post.id %}" class="btn btn-danger"><i class="fa fa-remove fa-fw"></i>Delete Post</a>
      </div>
    </div>
  </div>
  {% endfor %}

{% else %}
  <p>There are no posts</p>
  <p>Check back later</p>
{% endif %}
{% endblock %}

home/templates/home/index_unregistered.html
{% extends "base.html" %}
{% block content %}

<div class="row">
  <div class="col-md-12">
    <h1>Grapevine</h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <h3>Man is least himself when he talks in his own person. Give him a mask, and he will tell you the truth.</h3>
    <p> - Oscar Wilde</p>
  </div>
</div>


<div class="row jumbotron">
  <div class="col-md-6 text-center">
      <h3>If you have already registered please login</h3>
      <a href="{% url 'account:login' %}" class="btn btn-success"><i class="fa fa-sign-in fa-fw"></i>Login</a>
      <!-- TODO See if I can include the Login form -->
  </div>

  <div class="col-md-6 text-center">
      <h3>If you have an invite key please hit register</h3>
      <a href="{% url 'account:register' %}" class="btn btn-warning">Register</a>
      <!-- TODO See if I can include the Register form -->
  </div>

</div>
{% endblock %}

home/templates/home/new_post.html
{% extends "base.html" %}
{% block content %}

<div class="jumbotron">
  <form class="form-horizontal" role="form" method="POST" action="{% url 'home:new_post' %}">
    {% csrf_token %}
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
   <div class="form-group">
     <div class="col-sm-12">
       <!--<input type="text" class="form-control" name="username" id="username" placeholder="Enter Username"> -->
       <textarea class="form-control" name="post" id="post" placeholder="Share your story"></textarea>
     </div>
   </div>

   <div class="form-group">
     <div class="col-sm-offset-2 col-sm-10">
       <button type="submit" class="btn btn-primary">Post</button>
     </div>
   </div>
  </form>
</div>

{% endblock %}