account/urls.py
from django.conf.urls import url

from . import views

app_name = 'account'
urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^register/$', views.register, name='register'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^dash/$', views.dash, name='dash'),
    # Might be a better way to go about this one but just to test this is probably the best way....
    url(r'^create_new_invite_key/$', views.create_new_invite_key, name='create_new_invite_key'),

]

grapevine/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    # Admin
    url(r'^admin/', admin.site.urls),
    #  Home
    url(r'^', include('home.urls')),
    # Account
    url(r'^account/', include('account.urls')),
]

home/urls.py
from django.conf.urls import url

from . import views

# TODO Might Change this.... Might not!
app_name = 'home'
urlpatterns = [
    # Homepage
    url(r'^$', views.index, name='index'),
    # Details page
    url(r'^(?P<post_id>[0-9]+)/$', views.detail, name='detail'),
    # Add Comment
    url(r'^(?P<post_id>[0-9]+)/add_comment/$', views.addComment, name='add_comment'),
    # New Post
    url(r'^new_post/$', views.newPost, name='new_post'),
]

grapevine/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Grapevine - </title>
  <!-- Bootstrap css -->
  <link rel="stylesheet" type="text/css" href="{% static "bootstrap/css/bootstrap-theme.min.css" %}" />
  <link rel="stylesheet" type="text/css" href="{% static "bootstrap/css/bootstrap.min.css" %}" />
  <!-- Jansy Bootstrap TODO Still need to set up the new android style jasny menu-->
  <link rel="stylesheet" type="text/css" href="{% static "css/jasny-bootstrap.min.css" %}"/>
  <!-- Font Awesome. Oh yeah! -->
  <link rel="stylesheet" type="text/css" href="{% static "font-awesome-4.6.3/css/font-awesome.min.css" %}"/>
  <!-- Custom styling -->
  <link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}" />

  <!-- TODO Just for testing purposes -->
  <link rel="stylesheet" type="text/css" href="{% static "responsive-slides/css/responsiveslides.css" %}" />
{% include "header.html" %}
<div class="wrap">

<div class="container">
{% block content %} {% endblock %}
{% include "footer.html" %}
</div>

</div> <!-- End of wrap div -->
<!-- JQuery First-->
<script src="{% static "jquery/jquery-1.12.3.min.js" %}"></script>
<!-- Bootstrap Javascript -->
<script src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>
<!-- Jansy Bootstrap Javascript -->
<script src="{% static "js/jasny-bootstrap.min.js" %}"></script>


<!-- TODO Just for testing purposes -->
<script src="{% static "responsive-slides/js/responsiveslides.min.js" %}"></script>
</body>
</html>

grapevine/templates/footer.html
<footer>
<div class="row">
  <div class="col-md-12 text-center">
    <p class="bigger-p"><b>Donate via Bitcoin: <span class="">1Hx6FKSSv3p7iTrFNCDkZuwtSz9KVHt4Ap</span></b></p>
  </div>
</div>

<div class="row">
  <div class="col-md-12 text-center">
    <p>Grapevine &#169; 2016. All Rights Reserved</p>
  </div>
</div>
</footer>

grapevine/templates/header.html
<!-- Don't forget to add the links that are in the example to this project. Link to the site below -->
<!-- https://getbootstrap.com/examples/navbar-fixed-top/ -->
<!-- Set up the active class -->

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'home:index' %}"><i class="fa fa-home fa-fw"></i>Home</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'home:new_post' %}"><i class="fa fa-comment fa-fw"></i>New Post</a></li>
            {% endif %}
        </ul>

        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
          <li class="dropdown">
            <a href="{% url 'account:dash' %}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user fa-fw"></i>Account <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="{% url 'account:dash' %}"><i class="fa fa-dashboard fa-fw"></i>Dash</a></li>
              <li><a href="{% url 'account:logout' %}"><i class="fa fa-sign-out fa-fw"></i>Logout</a></li>
            </ul>
          </li>
          {% else %}
          <!-- TODO Might set this up so that there is a login form in the nav bar-->
          <li><a href="{% url 'account:login' %}"><i class="fa fa-sign-in fa-fw"></i>Login</a></li>
          <li><a href="{% url 'account:register' %}">Register</a></li>
          {% endif %}
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </nav>